# 验证操作（每一项操作完成后显示验证信息）
VERIFY='Y'

# 云服务器元数据覆盖（DNS 服务器、NTP 服务器、主机名、Docker 镜像）
METADATA='Y'

# 生产环境提醒（登录时提示生产环境）
PROD_TIPS='Y'

# 无响应注销时间（单位：秒）
LOGOUT_TIME='300'

# SSH 端口配置
SSH_PORT='22'

# 时区配置
TIME_ZONE='Asia/Shanghai'

# 主机名配置（开启云服务器元数据覆盖，云服务器会自动设置为元数据的主机名）
HOSTNAME='Narsil'

# DNS 服务器配置（开启云服务器元数据覆盖，云服务器会自动设置为元数据的 DNS 服务器）
DNS_SERVER='119.29.29.29 223.5.5.5'

# NTP 服务器配置（开启云服务器元数据覆盖，云服务器会自动设置为元数据的 NTP 服务器）
NTP_SERVER='ntp1.tencent.com ntp2.tencent.com ntp3.tencent.com ntp4.tencent.com ntp5.tencent.com'

# Docker Engine 配置
DOCKER_CE_REPO='https://mirrors.cloud.tencent.com/docker-ce'
